name: auto-building

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: check
        uses: actions/checkout@v4

      - name: install MinGW
        run: |
          choco install mingw -y
          echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH

      - name: build
        run: g++ -std=c++17 win.cpp -o wc.exe

      - name: up
        uses: actions/upload-artifact@v4
        with:
          name: wc
          path: wc.exe